modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory
license = "MIT"
[[mods]] #mandatory
modId = "tgears" #mandatory
version = "0.5.0" #mandatory
displayName = "Tinkers' Gears" #mandatory
logoFile = "icon.png"
authors = "Chemiofitor"
description = '''

'''
[[dependencies.tgears]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tgears]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tgears]]
modId = "create"
mandatory = true
versionRange = "[6.0.6,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.tgears]]
modId = "tconstruct"
mandatory = true
versionRange = "[3.10.1.0,)"
ordering = "AFTER"
side = "BOTH"